import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { NextAuthProvider } from './Providers';
import AuthButton from '@/components/AuthButton';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
  title: "保守管理システム",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <NextAuthProvider>
          <header style={{ padding: '1rem', borderBottom: '1px solid #ccc', marginBottom: '1rem' }}>
            <nav style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Link href="/">
                <h1>製品ライフサイクル管理</h1>
              </Link>
              <AuthButton /> {/* AuthButton を配置 */}
            </nav>
          </header>
          <main style={{ padding: '1rem' }}>
            {children}
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
